language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script: phpunit