<div class="wrap">
	<h1><?php _e( 'Custom Taxonomy Cleanup', 'custom-taxonomy-cleanup' ); ?></h1>
	<?php echo $notice; ?>
	<div class="notice">
		<p>
			<?php _e( 'There are no unused custom taxonomy terms found.', 'custom-taxonomy-cleanup' ); ?>
		</p>
	</div>
	<p>
		<?php 
			printf(
		 		/* translators: %s: wp-admin plugin page url */
				__( '<a href="%s">De-activate this plugin</a> or try again later.', 'custom-taxonomy-cleanup' ),
				esc_url( $plugin_url )
			);
		?> 
	</p>
	<hr>
	<p>
		<?php
			/* translators: %s: plugin link */
			printf( __( 'This page is generated by the %s plugin.', 'custom-taxonomy-cleanup' ), $plugin_link );
		?>
	</p>
</div>